#! /bin/bash

#   Add service file to runlevel directory

/bin/cp /etc/init.d/plymouth-openrc /etc/runlevels/default || true

#   Add service to runlevel

rc-update add plymouth-openrc default

#   Update services list

rc-update -u
